### ISSUE TITLE
Create PrometheeOutrankingFlows (M9 module)

### ISSUE THREAD

**Issue by WAndraszyk** [WAndraszyk/Construct-your-own-PROMETHEE-with-Python-for-MCDA#3]
Stworzyć podwaliny modułu M9 PrometheeOutrankingFlows.

**Comment by Tobias2705** [comment]
Rozpoczęcie prac nad modułem **M9 PrometheeOutrankingFlows** _(rozeznanie teoretyczne)_

**Comment by Tobias2705** [comment]
Wykonanie dokumentacji zaimplementowanych funkcjonalności
