### ISSUE TITLE
Create PrometheeIRanking (M11 module)

### ISSUE THREAD

**Issue by WAndraszyk** [WAndraszyk/Construct-your-own-PROMETHEE-with-Python-for-MCDA#4]
Stworzyć podwaliny modułu M11 PrometheeIRanking.

**Comment by Tobias2705** [comment]
Rozpoczęcie prac nad modułem **M11 PrometheeIRanking** _(rozeznanie teoretyczne)_

**Comment by Tobias2705** [comment]
Zaimplementowano funkcjonalności modułu M11

**Comment by Tobias2705** [comment]
Dokumentacja zaimplementowanych funkcjonalności
